### ISSUE TITLE
Unable import module "kmlread" in mavproxy SITL

### ISSUE THREAD

**Issue by ds-master** [ArduPilot/ardupilot_wiki#3706]
When I try to import kmlread module, it throws errors as follows:

STABILIZE> module load kmlread
STABILIZE> No module named 'wx'
Traceback (most recent call last):
  File "/home/ds-dev/.local/bin/mavproxy.py", line 649, in import_package
    mod = __import__(name)
  File "/home/ds-dev/.local/lib/python3.6/site-packages/MAVProxy/modules/mavproxy_kmlread.py", line 14, in <module>
    from MAVProxy.modules.mavproxy_map import mp_slipmap
  File "/home/ds-dev/.local/lib/python3.6/site-packages/MAVProxy/modules/mavproxy_map/mp_slipmap.py", line 19, in <module>
    from MAVProxy.modules.lib import win_layout
  File "/home/ds-dev/.local/lib/python3.6/site-packages/MAVProxy/modules/lib/win_layout.py", line 4, in <module>
    import os, wx, pickle
ModuleNotFoundError: No module named 'wx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ds-dev/.local/bin/mavproxy.py", line 496, in load_module
    m = import_package(modpath)
  File "/home/ds-dev/.local/bin/mavproxy.py", line 652, in import_package
    mod = __import__(name)
  File "/home/ds-dev/.local/lib/python3.6/site-packages/MAVProxy/modules/mavproxy_kmlread.py", line 14, in <module>
    from MAVProxy.modules.mavproxy_map import mp_slipmap
  File "/home/ds-dev/.local/lib/python3.6/site-packages/MAVProxy/modules/mavproxy_map/mp_slipmap.py", line 19, in <module>
    from MAVProxy.modules.lib import win_layout
  File "/home/ds-dev/.local/lib/python3.6/site-packages/MAVProxy/modules/lib/win_layout.py", line 4, in <module>
    import os, wx, pickle
ModuleNotFoundError: No module named 'wx'

No module named 'kmlread'
Traceback (most recent call last):
  File "/home/ds-dev/.local/bin/mavproxy.py", line 649, in import_package
    mod = __import__(name)
ModuleNotFoundError: No module named 'kmlread'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ds-dev/.local/bin/mavproxy.py", line 496, in load_module
    m = import_package(modpath)
  File "/home/ds-dev/.local/bin/mavproxy.py", line 652, in import_package
    mod = __import__(name)
ModuleNotFoundError: No module named 'kmlread'

Failed to load module: No module named 'kmlread'.

Is there anything I need to install before importing this module ?

**Comment by Hwurzburg** [comment]
this module loads fine for me....used the Tools/environment_install/install-prereqs-ubuntu.sh -y to install MAVProxy as part of the build environment per the wiki....I am assuming you followed this to install and for the correct python environment:https://ardupilot.org/mavproxy/docs/getting_started/download_and_installation.html...in any case, this should be a support question posted here:https://discuss.ardupilot.org/c/ground-control-software/mavproxy/73 instead of a wiki issue....closing
